name: Server CI

on:
  pull_request:
    branches:
      - main

jobs:
  server-test:
    runs-on: ubuntu-latest

    # Context Load 를 위한 MySQL Dokcer Service
    services: 
      mysql:
        image: mysql:8
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: ppalatjyo
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    defaults:
      run:
        working-directory: server

    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Create application.yml
        run: |
          mkdir -p src/main/resources
          cat <<EOT >> src/main/resources/application.yml
          spring:
            datasource:
              url: jdbc:mysql://127.0.0.1:3306/ppalatjyo
              username: root
              password: password
            jpa:
              hibernate:
                ddl-auto: create
          EOT

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew clean test
